package com.myspace.documentgenerator;


//from row number: 1
//Baseline
rule "Row 1 Account_Opening_Form"
	salience 1
	dialect "mvel"
	when
		crit : criteria( product == "Account Services" , subProduct == "Account Opening" , service == "New Account" , subService == "New Account" , audience in ( "client" ) )
	then
		crit.setDocumentDesc( "Request to open an account and acceptance of account terms and conditions." );
		crit.setDocumentPolicy( "BANK MANDATE" );
		crit.setInstructions( "Consult last page, as needed, for detailed instructions on each section." );
		crit.setDocumentGroup( "CLIENT TO COMPLETE AND SEND" );
		modify( crit ) {
				setDocumentName( "Account Opening Form" )
		}
		System.out.println("1 fired");
end

//from row number: 2
//Override
rule "Row 2 Account_Opening_Form"
	salience 2
	dialect "mvel"
	when
		crit : criteria( subChannel in ( "Non eBAM" ) , documentName == "Account Opening Form" )
	then
		crit.setDocumentCertification( "ORIGINAL" );
		crit.setDocumentPolicy( "BANK POLICY" );
		crit.setDocumentTemplate( "MXCCEC20181018021406_AOF" );
		System.out.println("2 fired");
end

//from row number: 3
//Override
rule "Row 3 Account_Opening_Form"
	salience 3
	dialect "mvel"
	when
		crit : criteria( subChannel in ( "Non eBAM" ) , residency in ( "Non-Resident" ) , documentName == "Account Opening Form" , region in ( "Western Europe" ) , country in ( "IRELAND" ) )
	then
		crit.setDocumentCertification( "SIMPLE COPY" );
		crit.setDocumentPolicy( "BANK POLICY" );
		crit.setDocumentTemplate( "MXCCEC20181221021235_AOF_Ireland" );
		System.out.println("3 fired");
end

//from row number: 4
//Override
rule "Row 4 Account_Opening_Form"
	salience 4
	dialect "mvel"
	when
		crit : criteria( subChannel in ( "Non eBAM" ) , residency in ( "Resident" ) , entityTypes in ( "Citi Entity", "Club and Societies", "Corporate - Irish Registered Public Listed Company (including known subsidiary)", "Corporate - Non Irish Public Listed Company (including known subsidiary)", "Corporate - Private Company", "Individual", "Institutional (Pension funds/Charity)", "Partnership", "Regulated Banks and Financial Institutions" ) , documentName == "Account Opening Form" , region in ( "Western Europe" ) , country in ( "IRELAND" ) )
	then
		crit.setDocumentCertification( "ORIGINAL" );
		crit.setInstructions( " VAT Number not required for resident entities." );
		System.out.println("4 fired");
end

//from row number: 5
//Override
rule "Row 5 Account_Opening_Form"
	date-effective "27-Mar-2019"
	date-expires "31-Mar-2019"
	salience 5
	dialect "mvel"
	when
		crit : criteria( subChannel in ( "eBAM Premier", "eBAM Standard" ) , documentName == "Account Opening Form" , region in ( "NA" ) , country in ( "UNITED STATES OF AMERICA" ) )
	then
		crit.setDocumentTemplate( "MXCCEC20180216044830_AOF_US_eBAM" );
		crit.setInstructions( "Please complete and return this form along with the eBAM Account Opening PDF." );
		System.out.println("5 fired");
end

