package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String test1;

	public test() {
	}

	public java.lang.String getTest1() {
		return this.test1;
	}

	public void setTest1(java.lang.String test1) {
		this.test1 = test1;
	}

	public test(java.lang.String test1) {
		this.test1 = test1;
	}

}